### ISSUE TITLE
console bugs

### ISSUE THREAD

**Issue by altsioma** [IvanMurakhovskii/react-tutorial#19]
Проверить ошибки в консоли.

![image](https://user-images.githubusercontent.com/62280973/97972118-58783300-1dc4-11eb-96ec-bb9506409632.png)

**Comment by IvanMurakhovskii** [comment]
Знаю, спасибо! В будущем исправлю!

**Comment by IvanMurakhovskii** [comment]
Исправлено. Предупреждения появляются, если в дочерние компоненты пробрасывать методы, который начинаются на on.
После переименования предупреждения пропали.
